{{- if and .Values.nginx.enabled .Values.nginx.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openops.fullname" . }}-nginx-config
  labels:
    {{- include "openops.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
data:
  nginx.conf: |-
    server {
      listen 80;
      
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      
      location / {
        proxy_pass http://{{ include "openops.fullname" . }}-app;
      }
      
      location /tables/ {
        proxy_pass http://{{ include "openops.fullname" . }}-tables/;
      }
      
      location /analytics/ {
        proxy_pass http://{{ include "openops.fullname" . }}-analytics/;
      }
    }
{{- end }}
