apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openops.fullname" . }}
  labels:
    {{- include "openops.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openops.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openops.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.secrets.enabled }}
            - name: OPS_OPENOPS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "openops.fullname" . }}
                  key: admin-password
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "openops.fullname" . }}
        {{- end }}
