{{- if .Values.tables.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openops.fullname" . }}-tables
  labels:
    {{- include "openops.labels" . | nindent 4 }}
    app.kubernetes.io/component: tables
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.tables.persistence.size }}
{{- end }}

---
{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openops.fullname" . }}-postgres
  labels:
    {{- include "openops.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}

---
{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openops.fullname" . }}-redis
  labels:
    {{- include "openops.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}

---
{{- if and .Values.engine.enabled .Values.engine.volumes.azure.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openops.fullname" . }}-azure
  labels:
    {{- include "openops.labels" . | nindent 4 }}
    app.kubernetes.io/component: engine
    app.kubernetes.io/volume-type: azure
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.engine.volumes.azure.size }}
{{- end }}

---
{{- if and .Values.engine.enabled .Values.engine.volumes.gcloud.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openops.fullname" . }}-gcloud
  labels:
    {{- include "openops.labels" . | nindent 4 }}
    app.kubernetes.io/component: engine
    app.kubernetes.io/volume-type: gcloud
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.engine.volumes.gcloud.size }}
{{- end }}
